create unique index IDX_MANAGEMENTPORTAL_CLIENT_UK_PHONE_NUMBER on MANAGEMENTPORTAL_CLIENT (PHONE_NUMBER) where DELETE_TS is null ;
create unique index IDX_MANAGEMENTPORTAL_CLIENT_UK_EMAIL on MANAGEMENTPORTAL_CLIENT (EMAIL) where DELETE_TS is null ;
create index IDX_MANAGEMENTPORTAL_CLIENT_EMAIL on MANAGEMENTPORTAL_CLIENT (EMAIL);
create index IDX_MANAGEMENTPORTAL_CLIENT_PHONE_NUMBER on MANAGEMENTPORTAL_CLIENT (PHONE_NUMBER);
