create unique index IDX_MANAGEMENTPORTAL_SUPPLIER_UK_EMAIL on MANAGEMENTPORTAL_SUPPLIER (EMAIL) where DELETE_TS is null ;
create index IDX_MANAGEMENTPORTAL_SUPPLIER_EMAIL on MANAGEMENTPORTAL_SUPPLIER (EMAIL);
