create unique index IDX_MANAGEMENTPORTAL_GUARD_UK_PHONE_NUMBER on MANAGEMENTPORTAL_GUARD (PHONE_NUMBER) where DELETE_TS is null ;
create index IDX_MANAGEMENTPORTAL_GUARD_PHONE_NUMBER on MANAGEMENTPORTAL_GUARD (PHONE_NUMBER);
create index IDX_MANAGEMENTPORTAL_GUARD_FIRST_NAME on MANAGEMENTPORTAL_GUARD (FIRST_NAME);
