-- begin MANAGEMENTPORTAL_ATTENDANCE
alter table MANAGEMENTPORTAL_ATTENDANCE add constraint FK_MANAGEMENTPORTAL_ATTENDANCE_ON_GUARD foreign key (GUARD_ID) references MANAGEMENTPORTAL_GUARD(ID)^
create index IDX_MANAGEMENTPORTAL_ATTENDANCE_ON_GUARD on MANAGEMENTPORTAL_ATTENDANCE (GUARD_ID)^
create index IDX_MANAGEMENTPORTAL_ATTENDANCE_TYPE_ on MANAGEMENTPORTAL_ATTENDANCE (TYPE_)^
-- end MANAGEMENTPORTAL_ATTENDANCE
-- begin MANAGEMENTPORTAL_SUPPLIER
create unique index IDX_MANAGEMENTPORTAL_SUPPLIER_UK_EMAIL on MANAGEMENTPORTAL_SUPPLIER (EMAIL) where DELETE_TS is null ^
create index IDX_MANAGEMENTPORTAL_SUPPLIER_EMAIL on MANAGEMENTPORTAL_SUPPLIER (EMAIL)^
-- end MANAGEMENTPORTAL_SUPPLIER
-- begin MANAGEMENTPORTAL_CLIENT
create unique index IDX_MANAGEMENTPORTAL_CLIENT_UK_PHONE_NUMBER on MANAGEMENTPORTAL_CLIENT (PHONE_NUMBER) where DELETE_TS is null ^
create unique index IDX_MANAGEMENTPORTAL_CLIENT_UK_EMAIL on MANAGEMENTPORTAL_CLIENT (EMAIL) where DELETE_TS is null ^
create index IDX_MANAGEMENTPORTAL_CLIENT_EMAIL on MANAGEMENTPORTAL_CLIENT (EMAIL)^
create index IDX_MANAGEMENTPORTAL_CLIENT_PHONE_NUMBER on MANAGEMENTPORTAL_CLIENT (PHONE_NUMBER)^
-- end MANAGEMENTPORTAL_CLIENT
-- begin MANAGEMENTPORTAL_GUARD
create unique index IDX_MANAGEMENTPORTAL_GUARD_UK_PHONE_NUMBER on MANAGEMENTPORTAL_GUARD (PHONE_NUMBER) where DELETE_TS is null ^
create index IDX_MANAGEMENTPORTAL_GUARD_PHONE_NUMBER on MANAGEMENTPORTAL_GUARD (PHONE_NUMBER)^
create index IDX_MANAGEMENTPORTAL_GUARD_FIRST_NAME on MANAGEMENTPORTAL_GUARD (FIRST_NAME)^
-- end MANAGEMENTPORTAL_GUARD
-- begin MANAGEMENTPORTAL_PAYMENT
alter table MANAGEMENTPORTAL_PAYMENT add constraint FK_MANAGEMENTPORTAL_PAYMENT_ON_CLIENT foreign key (CLIENT_ID) references MANAGEMENTPORTAL_CLIENT(ID)^
alter table MANAGEMENTPORTAL_PAYMENT add constraint FK_MANAGEMENTPORTAL_PAYMENT_ON_GUARD foreign key (GUARD_ID) references MANAGEMENTPORTAL_GUARD(ID)^
alter table MANAGEMENTPORTAL_PAYMENT add constraint FK_MANAGEMENTPORTAL_PAYMENT_ON_SUPPLIER foreign key (SUPPLIER_ID) references MANAGEMENTPORTAL_SUPPLIER(ID)^
create unique index IDX_MANAGEMENTPORTAL_PAYMENT_UK_TRANSACTION_CODE on MANAGEMENTPORTAL_PAYMENT (TRANSACTION_CODE) where DELETE_TS is null ^
create index IDX_MANAGEMENTPORTAL_PAYMENT_ON_CLIENT on MANAGEMENTPORTAL_PAYMENT (CLIENT_ID)^
create index IDX_MANAGEMENTPORTAL_PAYMENT_ON_GUARD on MANAGEMENTPORTAL_PAYMENT (GUARD_ID)^
create index IDX_MANAGEMENTPORTAL_PAYMENT_ON_SUPPLIER on MANAGEMENTPORTAL_PAYMENT (SUPPLIER_ID)^
create index IDX_MANAGEMENTPORTAL_PAYMENT_TRANSACTION_CODE on MANAGEMENTPORTAL_PAYMENT (TRANSACTION_CODE)^
-- end MANAGEMENTPORTAL_PAYMENT
